### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/generator-ng-poly#101]
With the recent changes to how our Gulpfile compiles/run apps and tests, adding other languages/versions shouldn't be too difficult anymore.

ES6 support using [6to5](https://github.com/6to5/6to5) or [Traceur](https://github.com/google/traceur-compiler) - maybe offer either as an option when the user selects ES6. Gulp should also inject these into index.html during the build process. I'm not sure if wiredep automatically adds these first, so might need to manually add them to the beginning of injected scripts.

Since we'd want to make it obvious these files are using ES6, it might be wise to use an .es6 extension. (Research what others are doing. AtScript project might have some suggestions.) We'll definitely want to use something like .es6 on the ng-poly side for storing the templates.

**Comment by DefunctExodus** [comment]
This would be very cool
+1

**Comment by drejohnson** [comment]
+1 for 6to5 support

**Comment by dustinspecker** [comment]
e20287f79485418637a1e77f47b3b8479b44a211 implemented using Babel (6to5). Not going to worry about Traceur at the moment because Babel seems to be to the go-to.
