### ISSUE TITLE
Separate bower and possibly npm files to make update easier

### ISSUE THREAD

**Issue by ngbinh** [dustinspecker/generator-ng-poly#102]
I am using ng-poly on a fairly complex frontend project at the moment and we need to pull in a number of different libraries through bower and npm. For that reason, updating ng-poly is a bit of nerve wrecking. I am wondering if there is a way to separate out the kind of bower libraries that ng-poly care about and the one that the app required? Separating npm may not be as big of the deal though.

**Comment by dustinspecker** [comment]
I don't think I understand. ng-poly, itself, doesn't use any of the dependencies from the generated project's Bower or npm dependencies.

Or do you mean separate the generated Bower and have users add to a different Bower directory? That'd be interesting, but I don't quite see the value.

**Comment by ngbinh** [comment]
Sorry I wasn't clear before. What I meant is when updating a build generated by old version of ng-poly with a new version of ng-poly. The main issue is usually updating bower.json file but I think I figure out a way now: grouping ng-poly and app specific together.
