### ISSUE TITLE
Test should reuse normal build artifact

### ISSUE THREAD

**Issue by ngbinh** [dustinspecker/generator-ng-poly#103]
With the latest update, I see unitTest and e2eTest are using separate build processes. I feel like that's not optimal because:
 - Need to maintain 3 different builds
 - Chance to slip bugs in because the production artifacts from production build didn't get tested but the test build artifacts.

I am not sure what is the main reason for the switch?

**Comment by dustinspecker** [comment]
There are two builds, sort of. The e2eTest build only compiles the e2e tests to /tmp, but it performs the test on the code in /build.

Hmm. You're right about the unit tests. Only the unit tests should be compiled to /tmp, not the entire application. I'll change this up.

**Comment by ngbinh** [comment]
Probably dup of #104
