### ISSUE TITLE
unitTest failed on prod build

### ISSUE THREAD

**Issue by ngbinh** [dustinspecker/generator-ng-poly#104]
`gulp unitTest --stage prod` is currently failing on `ng-poly` version `0.5.1` because all directives templates are deleted so all directive tests will fail.

**Comment by ngbinh** [comment]
I believe this one should be fixed along with https://github.com/dustinspecker/generator-ng-poly/issues/103 because they are related.

**Comment by dustinspecker** [comment]
Oh, good catch. This can be fixed by changing https://github.com/dustinspecker/generator-ng-poly/blob/00d40377d274a4f79d51392ce8a4a2f2561903d9/app/templates/_test.js#L44 to run bowerInject instead. I'll get this changed, too.

**Comment by ngbinh** [comment]
I am wondering why do we need to bowerInject again here? Can we do something like this:
 - `build` will build everything non-test to `buildDir`
 - `test` will build test resources and run against `buildDir` 

That way we actually test again the final result of the build.

**Comment by ngbinh** [comment]
Going down this path, I don't think we need `bowerInject` in `test.js`. So essentially, we don't really need `build:test`. At least for non-prod build, we don't need it. For prod build, this way have an issue because there are no `**/*directive.tpl.html`. I feel like the right path here is to extend `deleteTemplates` so that it will copy the templates to `tmp` on prod.

**Comment by dustinspecker** [comment]
I like that approach.

**Comment by dustinspecker** [comment]
2f5991dcca1499cead922dd2b39e86d306091a76 In prod, copies templates to tmp. Sorry for the mishaps and thanks for the suggestions.
