### ISSUE TITLE
Referencing image file from CSS --stage=prod vs dev

### ISSUE THREAD

**Issue by jack10** [dustinspecker/generator-ng-poly#106]
Hi Dustin, 

i have a problem with referencing a Image  File from `images` with a relative path. 
Due to CSS and JS gets minified for Production version the relative paths are not valid anymore. 
Example:
prod: `build/css/app-23094sd.css`
normal: `build/css/home/home.css`

I cant reference absolute paths since the Application does not get deployed under the root folder. Is there any way to get this working with relative Paths?  

Greetz
jack10

**Comment by dustinspecker** [comment]
Hey Jack10,

This should do the trick 64ef7fa16aca721b1af2c5ebd5dad495b0d158a9 . Thanks for catching this!
