### ISSUE TITLE
Installation error, ng-poly generator is not visible in generator list

### ISSUE THREAD

**Issue by tipodisimmia** [dustinspecker/generator-ng-poly#110]
My steps are:
1)npm install -g generator-ng-poly
2)npm install -g yo
3) npm install -g tsd@next

Node version: v0.10.25

Afeter yo ng-poly, i have this error:
Error ng-poly 
You don't seem to have a generator with the name ng-poly installed.

The installation procede with out error but the generator is not inserted in yoeman.

This is my  stack:

rrossi@pc-rrossi:~$ sudo npm install -g generator-ng-poly

[sudo] password for rrossi: 
npm WARN unmet dependency /usr/local/lib/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
generator-ng-poly@0.5.6 /usr/local/lib/node_modules/generator-ng-poly
├── ng-add-dep@0.2.0 (ng-mod-has-dep@0.1.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@1.0.2 (ansi-regex@1.1.0, string-length@1.0.0, ansi-styles@2.0.0, strip-ansi@2.0.1, pad-component@0.0.1, word-wrap@1.0.0, taketalk@1.0.0, minimist@1.1.0)
├── underscore.string@3.0.3
├── recursive-readdir@1.2.1 (minimatch@0.3.0)
├── findup-sync@0.2.1 (glob@4.3.5)
├── class-extend@0.1.1 (lodash@2.4.1)
├── update-notifier@0.3.0 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0, configstore@0.3.2)
├── lodash@3.2.0
└── yeoman-generator@0.18.9 (yeoman-welcome@1.0.0, read-chunk@1.0.1, dargs@3.0.1, detect-conflict@1.0.0, xdg-basedir@1.0.1, yeoman-assert@1.0.0, user-home@1.1.1, diff@1.2.2, rimraf@2.2.8, pretty-bytes@1.0.2, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.0, istextorbinary@1.0.2, debug@2.1.1, nopt@3.0.1, cross-spawn@0.2.6, run-async@0.1.0, mem-fs-editor@1.2.1, mkdirp@0.5.0, shelljs@0.3.0, cli-table@0.3.1, through2@0.6.3, dateformat@1.0.11, glob@4.3.5, github-username@1.1.1, file-utils@0.2.2, lodash@2.4.1, download@3.3.0, gruntfile-editor@0.2.0, sinon@1.12.2, cheerio@0.18.0, yeoman-environment@1.2.4, inquirer@0.8.0)
rrossi@pc-rrossi:~$ npm install -g yo

^Crrossi@pc-rrossi:~$ sudo npm install -g yo
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.4.5 postinstall /usr/local/lib/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ No .bowerrc file in home directory
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory

Everything looks all right!
npm WARN unmet dependency /usr/local/lib/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
yo@1.4.5 /usr/local/lib/node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.3.5
├── fullname@1.0.0
├── user-home@1.1.1
├── opn@1.0.1
├── async@0.9.0
├── lodash@2.4.1
├── sort-on@1.0.1 (dot-prop@1.0.1)
├── string-length@1.0.0 (strip-ansi@2.0.1)
├── humanize-string@1.0.1 (decamelize@1.0.0)
├── cross-spawn@0.2.6 (lru-cache@2.5.0)
├── yeoman-character@1.0.1 (supports-color@1.2.0)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@1.0.2 (ansi-regex@1.1.0, ansi-styles@2.0.0, strip-ansi@2.0.1, pad-component@0.0.1, word-wrap@1.0.0, minimist@1.1.0, taketalk@1.0.0)
├── root-check@1.0.0 (sudo-block@1.1.0, downgrade-root@1.1.0)
├── meow@3.0.0 (object-assign@2.0.0, minimist@1.1.0, camelcase-keys@1.0.0, indent-string@1.2.0)
├── update-notifier@0.3.0 (is-npm@1.0.0, latest-version@1.0.0, semver-diff@2.0.0)
├── npm-keyword@1.0.1 (registry-url@2.1.0, got@2.4.0)
├── package-json@1.0.2 (registry-url@2.1.0, got@2.4.0)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.0, graceful-fs@3.0.5, uuid@2.0.1, mkdirp@0.5.0, js-yaml@3.2.6)
├── insight@0.5.2 (object-assign@2.0.0, tough-cookie@0.12.1, lodash.debounce@2.4.1, os-name@1.0.3, request@2.53.0)
├── yeoman-environment@1.2.4 (log-symbols@1.0.1, escape-string-regexp@1.0.2, untildify@2.0.0, diff@1.2.2, text-table@0.2.0, debug@2.1.1, mem-fs@1.1.0, globby@1.1.0, grouped-queue@0.3.0, lodash@3.2.0)
├── yeoman-doctor@1.3.1 (log-symbols@1.0.1, object-values@1.0.0, each-async@1.1.1, twig@0.7.2)
└── inquirer@0.8.0 (ansi-regex@1.1.0, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, cli-color@0.3.2, rx@2.3.25)
rrossi@pc-rrossi:~$ sudo npm install -g tsd@next
npm WARN engine joi@4.9.0: wanted: {"node":">=0.10.30"} (current: {"node":"0.10.25","npm":"2.1.3"})
npm WARN engine topo@1.0.2: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"2.1.3"})
/usr/local/bin/tsd -> /usr/local/lib/node_modules/tsd/build/cli.js
npm WARN unmet dependency /usr/local/lib/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/express/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
tsd@0.6.0-beta.5 /usr/local/lib/node_modules/tsd
├── assertion-error@1.0.0
├── deep-freeze@0.0.1
├── joi-assert@0.0.3
├── type-detect@0.1.2
├── rimraf@2.2.8
├── jsesc@0.5.0
├── lru-cache@2.5.0
├── open@0.0.5
├── ministyle@0.1.4
├── minimist@1.1.0
├── uuid@2.0.1
├── exit@0.1.2
├── miniwrite@0.1.4 (mkdirp@0.3.5)
├── semver@4.3.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── uri-templates@0.1.5
├── bluebird@1.2.4
├── lazy.js@0.3.2
├── json-pointer@0.2.2 (foreach@2.0.5)
├── minimatch@1.0.0 (sigmund@1.0.0)
├── detect-indent@0.2.0 (get-stdin@0.1.0, minimist@0.1.0)
├── bl@0.9.4 (readable-stream@1.0.33)
├── event-stream@3.1.7 (stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, pause-stream@0.0.11, map-stream@0.1.0, split@0.2.10, through@2.3.6)
├── minichain@0.0.1
├── minitable@0.0.3 (minichain@0.0.1)
├── universal-analytics@0.3.6 (underscore@1.7.0, async@0.2.10, node-uuid@1.4.2)
├── glob@4.3.5 (inherits@2.0.1, inflight@1.0.4, once@1.3.1, minimatch@2.0.1)
├── joi@4.9.0 (topo@1.0.2, isemail@1.1.1, hoek@2.11.0, moment@2.9.0)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.9, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1)
├── definition-header@0.1.0 (xregexp@2.0.0, parsimmon@0.5.1)
├── verror@1.4.0 (extsprintf@1.0.3)
└── update-notifier@0.2.2 (is-npm@1.0.0, semver-diff@2.0.0, string-length@1.0.0, chalk@0.5.1, configstore@0.3.2, latest-version@1.0.0)

rrossi@pc-rrossi:~$ yo ng-poly
Error ng-poly 
You don't seem to have a generator with the name ng-poly installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.

**Comment by dustinspecker** [comment]
I'll try to research this tonight/tomorrow. I think I remember reading somewhere that installing yo and generators with sudo can cause issues (not 100% sure). Might try installing npm without sudo.

**Comment by xak2000** [comment]
Try `sudo chown -R your_user_name ~/.npm`
After that try installing without sudo.
Also try to update node to at least 10.0.33 and try to update npm `npm install -g npm@latest`

**Comment by tipodisimmia** [comment]
sudo chown -R your_user_name ~/.npm  and update to 10.0.33 is not working :( 
I have the same error....

**Comment by JavaTheHood** [comment]
1. remove nodejs
2. remove `~/.npm`
3. install node via nvm (https://github.com/creationix/nvm)
4. Install yo and generator-ng-poly WITHOUT SUDO!

Worked for me under Ubuntu 14.10
