### ISSUE TITLE
Wrong path to font files in urls of vendor css files

### ISSUE THREAD

**Issue by xak2000** [dustinspecker/generator-ng-poly#117]
In gulp's build file all font files copying to `fonts` folder.
It is ok for bootsrap as it has a structure of
/css
/fonts
/js

But in some other bower components fonts live not in /fonts folder which is one level upper then css file. For example in `ui-grid` library font files live at the same level as css files.
/bower_components/angular-ui-grid/ui-grid.css
/bower_components/angular-ui-grid/ui-grid.js
/bower_components/angular-ui-grid/ui-grid.woff

And of course in `ui-grid.css` all paths to font files are not `../fonts/*`.
```
@font-face {
  font-family: 'ui-grid';
  src: url('ui-grid.eot');
  src: url('ui-grid.eot#iefix') format('embedded-opentype'), url('ui-grid.woff') format('woff'), url('ui-grid.ttf?') format('truetype'), url('ui-grid.svg?#ui-grid') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
So after build and open site in browser font files are not found as they now in `/fonts` folder. But css file which need them in `/css` folder.

*Note:* As mentioned in #116 I working on project generated by old version of generator-ng-poly. Maybe this problem already fixed in last version. I will try to generate a new project and ivestigate further.

*Note2:* I created a new project with last version of generator-ng-poly and this "bug" is still here.

**Comment by xak2000** [comment]
Maybe we need to not split vendor packages to js/css/etc but leave it as is.
For example for bootstrap it will be (from main section of bootstrap's bower.json):
```
/vendor/bootstrap/less/bootstrap.less
/vendor/bootstrap/dist/css/bootstrap.css
/vendor/bootstrap/dist/js/bootstrap.js
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
```

In this case all paths to fonts/images/whatever in css files (and any files with paths inside) will be correct.

But this solution only for dev mode. When all vendor js and css files will be minified and concatenated all paths will be broken.

**Comment by xak2000** [comment]
For minify algorythm we can calc diff betwen not minified css path and minified css path and then apply that diff to each URL in css. In this case all files except js and css must be leaved as is and not copied into /fonts, /images etc.

So for bootstrap example minified file structure will be:
```
/vendor/vendor-123456765.css
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
```
Before minify we will convert all URLs in css to absolute relatively to path `/vendor/bootstrap/dist/css` and after minify we will convert them back to relative but relatively to path `/vendor`.

Maybe there are better way. It is just my thoughts about this problem.

**Comment by dustinspecker** [comment]
Hmm. Good catch. This sounds like a similar solution to what we had to do for image URLs for app CSS. We just made the URLs relative for that. I think to keep this as simple as possible, we can detect the font URLs and make sure everything is pointed to the correct font directory in dev and prod after we move all fonts to /fonts. We made [gulp-modify-css-urls](https://github.com/dustinspecker/gulp-modify-css-urls) last time and that might do the trick again.

**Comment by xak2000** [comment]
Maybe you right but it will fix only fonts.

I think this bug also actual for vendor images but can't find the task for copy vendor images anywhere.
But I think if any of library will have image files we need to copy them to /vendor/images as well and fix css URLs for images as well.

Maybe there are something else except fonts and images that also needs to fix paths? I can't imagine now. But if we leave directory structure for vendor libraries as is (except css and js files) we can just fix ALL urls in css files and that will guarantee all futher possible cases.
Иut maybe I'm getting too far ahead. :) Maybe you are right and specific solution is better.

Also if you will work on fix for this bug there are another font extension `woff2` that we need to add to fonts filter.

**Comment by jack10** [comment]
for the images I fixed the bug, by adding the bowerfiles in to `build/images/`

```javascript
// copy and optimize images into build directory
gulp.task('images', ['clean'], function () {
  var imageFilter = $.filter('**/*.{jpg,png,gif}');
  return gulp.src(
      $.mainBowerFiles().concat([appImages])
  )
    .pipe(imageFilter) 
    .pipe($.if(isProd, $.imagemin()))
    .pipe(gulp.dest(buildConfig.buildImages));
});
```
Its still not the best way to fix the css path. 

in `bowerCopy`-Task
```javascript
  return stream.done()
    .pipe(cssFilter)
    .pipe($.cssUrlAdjuster({
      replace: ['images/','../images/']
    }))
    .pipe($.if(isProd, $.concat('vendor.css')))
    .pipe($.if(isProd, $.cssmin()))
    .pipe($.if(isProd, $.rev()))
    .pipe(gulp.dest(buildConfig.buildCss))
...
```
in my case  it works, but if there are some urls that reference images without the `image/` prefix it might not work. 

Another thing I stumbled upon, is that some project might not have images included in the `main`-property in their `bower.json`.

I think [gulp-modify-css-urls](https://github.com/dustinspecker/gulp-modify-css-urls) might be a solution here, because you can parse the URL and therefore sort by file-endings.

**Comment by dustinspecker** [comment]
I'm thinking Jack's approach will be best here. For the projects that don't specify images in the main property, users will need to override them in their project's bower.json.

**Comment by xak2000** [comment]
Jack's approach will work only for images from urls with `images/*.*` in it. There are the same problem as with fonts. If any images referenced from css as `img/*.*` or just `any.jpg` without path then it will not work. We need somehow to replace full path except filename to our path to vendor images.

**Comment by dustinspecker** [comment]
My bad. Yeah, I think it's best that we move all Bower images and fonts to the same folder (images/ and fonts/). We then check every CSS URL and rewrite it appropriately like we do the for the source CSS. For example, any image file will then point to this images folder. This isn't ideal.

**Comment by xak2000** [comment]
We can then come into names collision.
For example if one library has file named `button.jpg` and other library has image named `button.jpg`. This is less actual for fonts as usually fonts with same name are really the same. But...

**Comment by dustinspecker** [comment]
Another great point...

**Comment by dustinspecker** [comment]
Maybe there's an elegant way to move all images to a folder with the name of the respective Bower component and inject that name into the CSS URLs. Sort of like what you've mentioned earlier.

```
build/
  images/
    bootstrap/
      btn.jpg
    foundation
      btn.jpg
```

**Comment by xak2000** [comment]
But again. What if one library has for example themes. And each theme has images with same name.
I think the only 100% free from bugs way is to leave vendor's directory structure as is as I mentioned earlier. But for minify css we still need some algorithm to modify resources urls based on relative path from each css to each resource to relative path from new minified css to each resource.

**Comment by dustinspecker** [comment]
Oh, yeah. Hmmm. We might be able to use [gulp-css-rebase-urls](https://www.npmjs.com/package/gulp-css-rebase-urls) for that.

**Comment by xak2000** [comment]
Hmm. Yes from their examples I think [gulp-css-rebase-urls](https://www.npmjs.com/package/gulp-css-rebase-urls) can be useful for this.

**Comment by dustinspecker** [comment]
b6891568490d48778c5c193bbef4c56e7554edb0 I believe this fixes the vendor asset URL issue.

**Comment by xak2000** [comment]
Maybe then remove `fontsBower` task and include copying of all bower files except js and css into `bowerCopy` task? Because now bower fonts isn't something special to consider as all bower files except js and css must be copied into `buildConfig.extDir`. Fonts, images, etc. Who knows what else can be included in mainBowerFiles of some library.

Maybe open another issue for that as this issue is for fonts and I think this is fixed (not tried myself yet).
