### ISSUE TITLE
How to load 'child' modules into 'parent' modules from Deep Level Example

### ISSUE THREAD

**Issue by kaned** [dustinspecker/generator-ng-poly#118]
I am new to Angular, ui-router and generator-ng-poly and am hoping someone can help with what is likely a simple syntax issue.

I am using geneartor-ng-poly for a new project and working from the "Deep Level Example" with an Angular 1.3 based app using ui-router and HTML.

First I created a "home" module, then a "header" module inside that. So...

    yo ng-poly:module home
    yo ng-poly:module home/header

Which gives me the two controllers: app/home/home.js and app/home/header/header.js

Now I want to use the "header" from within home.tpl.html and I am struggling with how to do this. From what I understand either

    <div ui-view=“header”></div>
    or
    <div ui-view=“home.header”></div>

should work, but neither is. Hours of Googling has not helped since all the examples use the more common $stateProvider format where there are chained states.

How should I be referencing "header" to have it show up properly inside home.tpl.html?

**Comment by dustinspecker** [comment]
Hey Kaned. This isn't how states should be treated, in my opinion. States should describe the application's current *state*. Sounds like you're actually just wanting to import a header template into your home view. If that's the case, I'd encourage looking into directives. Directives can have templates. From there, just use the directive you made inside the home view.

**Comment by kaned** [comment]
Thanks Dustin, I'll check them out.

Kane

**Comment by kaned** [comment]
Dustin set me right on this. That I should be looking at directives instead of modules and that worked right away. Thanks Dustin!
