### ISSUE TITLE
Bootstrap UI not Angular 1.3 compatible

### ISSUE THREAD

**Issue by wilsonwc** [dustinspecker/generator-ng-poly#120]
Bootstrap UI is not 100% Angular 1.3 compatible, so if it's possible to disable that option for >1.3 projects that might lead to less confusion among some users

**Comment by dustinspecker** [comment]
Thanks for the heads up! I hadn't realized that.

**Comment by dustinspecker** [comment]
f54d5511be4632ebf42124cb651013bdcce82f7c Stopped offering it on 1.3.x for the time being.
