### ISSUE TITLE
Don't generate body CSS for views

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/generator-ng-poly#126]
This is often just deleted by users.

**Comment by xak2000** [comment]
You mean `body` rule in generated `.less` files? It is for example of course but yes, it is always just deleted.

**Comment by dustinspecker** [comment]
Yep, exactly. I should have written that better.

**Comment by dustinspecker** [comment]
36cf8f0c549c35dc5826ae356f823eb34503b447
