### ISSUE TITLE
When running yo ng-poly on windows, the process hangs

### ISSUE THREAD

**Issue by ms-clovis** [dustinspecker/generator-ng-poly#131]
I have tried numerous times to run ng-poly(app) and after asking the required questions, the process begins to install. Every time the process hangs (the command prompt) at the following:

angular-animate#1.3.15 bower_components\angular-animate
└── angular#1.3.15
   create app\home\home.js
   create e2e\home\home.po.js
   create e2e\home\home_test.js
   create app\home\controllers\home-controller.js
   create app\test\home\controllers\home-controller_test.js
   create app\home\views\home.tpl.html
   create app\home\views\home.css

I disabled my personal firewall and it did not change the behavior. Has anyone seen this behavior before?

**Comment by dustinspecker** [comment]
Hey. Are you using Node 0.12 by any chance? I've noticed this happening, too. At that point in the process, you can CTRL+C and everything is setup just fine (I know, not a great solution at all). I just tried Node 0.10 and it doesn't hang at all. I'm curious if this is related to https://github.com/yeoman/generator/issues/778.

Sorry for the inconvenience.

**Comment by ms-clovis** [comment]
Dustin,
     Thanks for getting back so quickly. Yes, I was using 0.12 of Node. 
I had used CTRL + C out of necessity and am glad everything is alright.  
Thanks for creating the generator.

Have a great day,

Mike

**Comment by busches** [comment]
I'm having the same issue with io.js 1.6.2 and npm 2.7.1 on Windows 7x64. After running the generator it hangs and does the same when running `npm install`, command line shows it's calling `git-remote-https.exe` but there's no network traffic happening.

**Comment by dustinspecker** [comment]
Looks like Node v0.12.2 fixes the issue.
