### ISSUE TITLE
Replace gulp-plato with just plato

### ISSUE THREAD

**Issue by busches** [dustinspecker/generator-ng-poly#132]
Fresh install is reporting `npm WARN deprecated gulp-plato@1.0.2: Deprecated. Just use the `plato` module directly.`

**Comment by dustinspecker** [comment]
7ec79a4d6f9b1196ea5543d680b52e83f5a52672 bd42f4b49772678e11088379a34833a28c492ecd Fixed. Thanks for bringing this up!
