### ISSUE TITLE
Module selection dialog show only 5 first modules

### ISSUE THREAD

**Issue by xak2000** [dustinspecker/generator-ng-poly#141]
I try to add new factory

```
$ yo ng-poly:factory auth
? Which module is this for? 
❯ app 
  app/models 
  app/libs 
  app/libs/moment 
  app/libs/lodash 
```

List for module selection shows only 5 first modules. Moving arrow down not show other modules but instead just circle this 5. I dont know when this broken. But I remember that before I saw full list of my angular modules after moving arrow down.

`yo ng-poly:factory auth --module=components/auth` works fine.

My other modules named `components` and `views` with submodules in them (if that matters).

**Comment by dustinspecker** [comment]
Ooo, this is going to be fun to fix.

So, in an update we "fixed" the module list by making sure the components directory was not displayed because that's where we put custom Polymer elements We also disabled views along with other Angular component types when we added the module-type structure.

I'll look into this tonight and see if we can be smarter. I'm really sorry about the inconvenience.

**Comment by xak2000** [comment]
Hmm.. I did think that module list is collecting by parsiong `.js` files for `.module('components.auth', [` or something similar. I did not think that it is just existing directories.

But don't worry. `--module=components/auth` works fine so this bug is not too critical.

**Comment by dustinspecker** [comment]
`v0.10.4` will no longer hide the `views/`, etc. directories when using a `module-only` structure.

Working on only ignoring `components/` when Polymer is installed.

**Comment by xak2000** [comment]
Maybe we can consider directories as modules only if in this directory there are `.js` file with name of this directory or `[name_of_this_directory]-module.js? And then not blacklist any directories at all.

**Comment by dustinspecker** [comment]
That's a way better idea. Great idea. Thanks!

**Comment by dustinspecker** [comment]
`v0.10.5` does what you proposed. Thanks again for the idea and sorry for the very long delay in fixing this bug.

**Comment by xak2000** [comment]
Would it work for old-stype `module-name.js` (without `-module` suffix)? I still have some in my project.
But if not I think I can rename them...

**Comment by dustinspecker** [comment]
Requires `-module` suffix.
