### ISSUE TITLE
Is build necessary for e2eTest

### ISSUE THREAD

**Issue by wilsonwc** [dustinspecker/generator-ng-poly#145]
I am not sure that the build step is completely necessary, and at least in my scenario, it is redundant for the e2eTest task.  e2e requires that dev or something similar has already been run to start up the server, and in that case it is watching/compiling. On running the e2e task another build is done without any files actually changing.

**Comment by dustinspecker** [comment]
Good call. Should be removed from the task list.

**Comment by dustinspecker** [comment]
3a196b954f94f86d9abe675b30f771a8a08de840 done
