### ISSUE TITLE
Error with route generator

### ISSUE THREAD

**Issue by irthos** [dustinspecker/generator-ng-poly#150]
any ideas? I've uninstalled ng-poly and yo, cleared npm's cache, reinstalled yo and ng-poly but still get the following error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at writing (/usr/local/lib/node_modules/generator-ng-poly/route/index.js:62:19)
    at /usr/local/lib/node_modules/generator-ng-poly/node_modules/yeoman-generator/lib/base.js:412:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by karbassi** [comment]
:+1: Same.

This is with v0.8.3

**Comment by dustinspecker** [comment]
Hmm. I haven't been able to reproduce this. Could you provide more info? The .yo-rc.json file would be good to see, too. Also, was this project generated with an older version or with 0.8.3?

**Comment by karbassi** [comment]
@dustinspecker 

This is off a fresh project. Just did `yo ng-poly`, answered the questions, and did `yo ng-poly:route company-view`.

Here is my `.yo-rc.json` file: 
```json
{
  "generator-ng-poly": {
    "structure": "module-only",
    "markup": "jade",
    "appScript": "js",
    "controllerAs": true,
    "skipController": false,
    "testScript": "js",
    "testFramework": "jasmine",
    "e2eTestFramework": "jasmine",
    "style": "scss",
    "ngRoute": false,
    "lastUsedModule": "home"
  }
}
```

**Comment by irthos** [comment]
I've updated node and npm to the latest and that stops the error for me. When I run the route generator, everything works so long as i select the home module or another created module but if i choose the app-level module, then the generator breaks with the same error:

    ? Which module is this for? app
    ? What's the URL for this route? /rootroute
    ? What's the templateURL for this route? /rootroute.tpl.html
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    TypeError: path must be a string
        at TypeError (native)
        at Object.fs.openSync (fs.js:500:18)
        at Object.fs.readFileSync (fs.js:352:15)
        at writing (/usr/local/lib/node_modules/generator-ng-poly/route/index.js:62:19)
        at /usr/local/lib/node_modules/generator-ng-poly/node_modules/yeoman-generator/lib/base.js:412:16
        at processImmediate [as _immediateCallback] (timers.js:358:17)

### .yo-rc.json
`
    {
      "generator-ng-poly": {
        "appScript": "coffee",
        "controllerAs": true,
        "e2eTestFramework": "jasmine",
        "markup": "html",
        "ngRoute": false,
        "structure": "module-only",
        "style": "scss",
        "testFramework": "jasmine",
        "testScript": "coffee",
        "lastUsedModule": "home"
      }
    }
`

**Comment by dustinspecker** [comment]
Ah. I forgot where, but there's a discussion in an issue here that we don't have support for adding routes to the main app module.

Looks like we should revise that with people trying to do that. I'll add this to the list of stuff to get working.

**Comment by irthos** [comment]
cheers dustin! thanks for clearing that up, it's not much of a drawback.. for better or worse, i'm used to defining all my routes on the top level app. (a few times i've done routing in submodules tho it's easier to see my app's states at a glance when they're in the same place)

**Comment by dustinspecker** [comment]
84bbfb59f0a83bbaa77487717f424957e5732ace Able to add route to app module.

**Comment by irthos** [comment]
You're the man!
