### ISSUE TITLE
$window Properties Problems in Production 

### ISSUE THREAD

**Issue by jordond** [dustinspecker/generator-ng-poly#151]
I am having a problem when running gulp for production.  In development mode this line of code works perfectly:

    var test = angular.element($window).width();

However in production mode I get a:
  

    Uncaught TypeError: angular.element(...).width is not a function(anonymous function)

This isn't the first time I encountered this problem, but previously I found a workaround.  I was wondering if there is a way to fix this instead.

**Comment by dustinspecker** [comment]
Sorry for the late response.

Interesting. Could I ask what the work around is? Could you also provide more code so I can better understand? I'm guessing this is probably more likely a probably with ng-annotate or something, but if ng-poly can do something to help then that's awesome.

**Comment by jordond** [comment]
Well currently the workaround is to use a jQuery wrapper instead, however jslint, and eslint throw a bunch of warnings, so I have to temporarily disable them for that section.

ie:

     '$(window).width()'

Here is another example for code that worked in dev, but not in prod.

    link: function (scope, element, attrs) {
        var $win = angular.element($window)
        , topClass = attrs.addClassOnScroll
        , offsetTop = element.offset().top;
    
        $win.on('scroll', function () {
          if ($win.scrollTop() >= offsetTop) {
            element.addClass(topClass);
          } else {
            element.removeClass(topClass);
          }
        });
      }

It fails on the 'element.offset().top' and '$win.scrollTop()'.  So I just switched to jquery $(), and set a comment for eslint to ignore some warnings, as a workaround. 

And the workaround
    
    link: function (scope, element, attrs) {
        /*jshint undef:false */
        /*eslint-disable*/
        var topClass = attrs.addClassOnScroll
        , offsetTop = $(element).offset().top;
    
        $win.on('scroll', function () {
          if ($($win).scrollTop() >= offsetTop) {
            element.addClass(topClass);
          } else {
            element.removeClass(topClass);
          }
        });
        /*jshint undef:true */
        /*eslint-enable*/
      }

Not ideal, but it works for now.

**Comment by dustinspecker** [comment]
Hmm. That's odd. It sounds like an ng-annotate issue. Have you looked at the output to verify the dependency injection is being added appropriately?

**Comment by dustinspecker** [comment]
I'm going to close this. If anyone runs into this and believes it's something ng-poly can fix, we can open this back up.
