### ISSUE TITLE
Problem with injecting Paper-Elements

### ISSUE THREAD

**Issue by happschinson** [dustinspecker/generator-ng-poly#158]
Hi!
If I want to use the paper-button for example, i know i need to add it to my build.js file.
I changed it to: 

.pipe($.addSrc([
        bowerDir + 'polymer/{layout,polymer}.{html,js}',
        bowerDir + 'paper-button/paper-button.html'
      ], {base: bowerDir}))

but 
<paper-button raised>raised button</paper-button>

still only gives me a blank text "raised button" without the element.

What am I doing wron?

**Comment by dustinspecker** [comment]
Hey. This is where it gets kind of tedious...

paper-button also requires the dependencies listed in its [bower.json](https://github.com/Polymer/paper-button/blob/upstream_v0_5/bower.json). So, each of those will need to be added to this list.

**Comment by dustinspecker** [comment]
If this didn't work for you, feel free to reopen this issue.
