### ISSUE TITLE
Missing files in test coverage report

### ISSUE THREAD

**Issue by havok2905** [dustinspecker/generator-ng-poly#159]
Currently when I run unit tests, the coverage directory and files are created but show 0 lines, statements, branches, or functions, with ignored as 'none', and all at 100% coverage. Here are the steps it took me to duplicate the issue. I am on npm version 2.1.5, and node version 0.10.26.

- I updated the ng-poly generator
- Scaffolded a new project with a constant and factory to generate sample unit tests
- Ran gulp unitTest and confirmed that the coverage directory was rebuilding itself
- Opened the index.html file in ./coverage

**Comment by dustinspecker** [comment]
Hey. That's odd. Can you provide your `.yo-rc.json` and `build.config.js`? Sorry for the inconvenience.

**Comment by havok2905** [comment]
build.config.js
```'use strict';

module.exports = {
  host: 'localhost',
  port: 3000,

  // app directories
  appDir: 'app',

  // unit test directories
  unitTestDir: 'app',

  // build directories
  buildDir: 'build/',
  buildCss: 'build/css/',
  buildFonts: 'build/fonts/',
  buildImages: 'build/images/',
  buildJs: 'build/js/',
  extDir: 'build/vendor/',
  extCss: 'build/vendor/css/',
  extFonts: 'build/vendor/fonts/',
  extJs: 'build/vendor/js/'
};```

.yo-rc.json
```{
  "generator-ng-poly": {
    "markup": "html",
    "appScript": "js",
    "controllerAs": true,
    "skipController": true,
    "passFunc": true,
    "namedFunc": true,
    "testScript": "js",
    "testFramework": "jasmine",
    "e2eTestFramework": "jasmine",
    "style": "css",
    "ngRoute": false,
    "lastUsedModule": "home"
  }
}```

**Comment by havok2905** [comment]
I was able to dig a little deeper and discovered that this was the result of a bizarre file permissions issue with yeoman and npm updating the generator on my dev environment. It would cache the new version but never install it globally. I'm so sorry for the false alarm and thank you for the quick response.

**Comment by dustinspecker** [comment]
No worries! Glad to hear it's working.

**Comment by csojka** [comment]
I worked with havok2905 on this and we're still seeing this issue. I was trying to debug the issue and was unclear how to force the lcov stuff to run. Any thoughts?

**Comment by dustinspecker** [comment]
Can you verify you're using a recent version of ng-poly? `npm list -g generator-ng-poly --depth=0` will show you the current version installed.

The coverage directory is all done in `karma.config.js`.

**Comment by csojka** [comment]
/Users/csojka/npm/lib
└── generator-ng-poly@0.8.3

If I've already generated my project does it matter? I'm a few months into the project.

Here's the current karma config. It appears to 

```
'use strict';
var buildConfig = require('./build.config.js')
  , isProd = require('yargs').argv.stage === 'prod'
  , preprocessors = {}
  , buildDir
  , jsDir
  , coverageReporter;

buildDir = (isProd ? 'tmp/' : '') + buildConfig.buildDir;
// add slash if missing to properly strip prefix from directive templates
if (buildDir[buildDir.length - 1] !== '/') {
  buildDir = buildDir + '/';
}

jsDir = 'tmp/' + buildConfig.buildJs;
// add slash if missing to properly strip prefix from directive templates
if (jsDir[jsDir.length - 1] !== '/') {
  jsDir = jsDir + '/';
}

coverageReporter = {
  type : 'lcov',
  dir : 'coverage/'
};

preprocessors[jsDir + '**/*.js)'] = ['coverage'];
preprocessors[buildDir + '**/*-directive.tpl.html'] = ['ng-html2js'];

module.exports = {
  browsers: ['PhantomJS'],
  frameworks: ['jasmine', 'sinon'],
  reporters: ['failed', 'coverage'],
  preprocessors: preprocessors,
  coverageReporter: coverageReporter,
  ngHtml2JsPreprocessor: {
    stripPrefix: buildDir
  },
  singleRun: true
};
```

![2015-06-24_17-02-37](https://cloud.githubusercontent.com/assets/13024896/8343448/a8a2deec-1a92-11e5-9b87-73a3d68b7663.png)

**Comment by dustinspecker** [comment]
I think that Karma config was generated with an older version [0.8.3](https://github.com/dustinspecker/generator-ng-poly/blob/v0.8.3/app/templates/_karma.config.js).

You can try making the changes from this [commit](https://github.com/dustinspecker/generator-ng-poly/commit/acb4b2d0095bbf27b89e973d167c04bfd16f0e1d) and see if that fixes the issue. Depending on what version of ng-poly was used, this should fix the issue.

If that doesn't work, I really think the best bet is to scaffold a new app and then copy over the `Gulpfile.js`, `karma.config.js`, `gulp/` directory, and `build.config.js` to the existing project. Tedious, but that would provide an up-to-date Gulp and Karma setup.

If the latter solution won't work, then let me know how the first solution goes and we're go from there.

Sorry for the inconveniences.

**Comment by csojka** [comment]
Would I also need to change my build.config.js to match?

**Comment by dustinspecker** [comment]
Oh, yeah. That might need to be updated, too.

**Comment by csojka** [comment]
It was two things, the js to be tested in the preprocessor was looking for a 'tmp' directory and then the "build/**/*.js" so this fixed that (rather than copying all the files):

jsDir = (isProd ? 'tmp/' : '') + buildConfig.buildJs;

Also, in that commit you mentioned,  removing the ')' from the line:
preprocessors[jsDir + '**/*.js)'] = ['coverage'];
