### ISSUE TITLE
Clarification on JS Inject

### ISSUE THREAD

**Issue by irthos** [dustinspecker/generator-ng-poly#161]
How does the system know which js files to inject from a bower repo? Or how to specify which .js files to include or not. (ex. In the case of bootstrap, i may want to grab the .css but not the .js)

Thanks!

**Comment by dustinspecker** [comment]
Hey. We're using [Wiredep](https://github.com/taptapship/wiredep) to inject JS and CSS. Wiredep respects overrides in `bower.json` as described in [Wiredep's Bower Overrides](https://github.com/taptapship/wiredep#bower-overrides).

I'll add to the README later to make it clear we're using Wiredep.

**Comment by irthos** [comment]
Ok thanks dustin!
