### ISSUE TITLE
'"tsd reinstall && tsd rebundle"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by erezak** [dustinspecker/generator-ng-poly#163]
When generating an app with the options listed below, the tsd step fails. However, it does work from the command line outside the script

Angular Version – 1.3
Structure – Feature based
Markup – HTML
Language – TypeScript
Controller as – Yes
Test Language – TypeScript
UT – Jasmine
E2E – Jasmine
Style – CSS
Polymer – No
Framework – None
ngRoute – No
Additional – None

**Comment by dustinspecker** [comment]
Thank you. This is now fixed in 80170ec113185ca512a2feba5eaee14b1f2825ca.
