### ISSUE TITLE
Installing other bower packages

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#172]
Will installing other bower packages automatically included when building (using gulp) the app? Like for example, I might install Restangular in the future, can I just do this:

bower install restangular --save

and the gulpfile.js will take care of everything?
Or do I have to manually edit some files after installing a bower package? Thanks.

**Comment by dustinspecker** [comment]
We use [Wiredep](https://github.com/taptapship/wiredep) in the Gulpfile, so as long as the Bower package defines its main files, Wiredep will make sure to load and inject the Bower dependencies in the correct order.
