### ISSUE TITLE
Can I start using the ES6 codebase?

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#173]
Since ES6 has now been officially released, I guess its ok to start using it? Is ng-poly es6 code safe to use for my new commercial app/project?

**Comment by dustinspecker** [comment]
ng-poly uses Babel, so ES6/2015 will be transpiled to ES5. It should be good to go in regards to that. If you find any bugs or have suggestions on how we can improve the setup please let us know.
