### ISSUE TITLE
generator-ng-poly@0.10.2 not visible in yeoman

### ISSUE THREAD

**Issue by smorandi** [dustinspecker/generator-ng-poly#178]
when installing the ng-poly generator (npm install -g generator-ng-poly) with the latest revision (0.10.2) from scratch it does not show up in yo --generators. 0.10.1 works fine.

using windows-8.1-x64 with npm 2.11.2 in an admin console.

**Comment by dustinspecker** [comment]
Should be fixed now in 0.10.3. Thanks for catching that! Sorry about that.
