### ISSUE TITLE
Add ui-bootstrap as an option for Angular 1.4 & 1.3?

### ISSUE THREAD

**Issue by jancel** [dustinspecker/generator-ng-poly#182]
Ui-Bootstrap 0.13.3 states AngularJS (requires AngularJS 1.3.x, tested with 1.4.3). 0.12.0 is the last version of this library that supports AngularJS 1.2.x.

I'm having better luck integrating 1.4.x Angular with Ui-bootstrap (moreso than AngularStrap) but missing all of the goodies unless I generate at a lower level and move angular up separately. 

Suggestions?

**Comment by dustinspecker** [comment]
Thanks. I'll look into adding support for it for newer Angular versions. I haven't paid attention to UI Bootstrap, so thanks for catching this update.

**Comment by dustinspecker** [comment]
bd1ee1754cd1260ebffdfb11c59a31ad41634365 added. Thanks again for catching this.
