### ISSUE TITLE
Drop support for command line options for controller-as and ng-route

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/generator-ng-poly#184]
Projects should **definitely** not be using both ngRoute and UI Router. Also, projects should consistently use controllerAs.

**Comment by flipjs** [comment]
Are we doing away with ui-router? I haven't paid attention to angular scene lately. Is there a new better (es5) router?

**Comment by dustinspecker** [comment]
We're keeping UI Router. Sorry for the confusion. When scaffolding a module or route, you can pass an argument like `yo ng-poly:module navigation --ng-route=false` which tells ng-poly which router to generate files for. Projects should scaffold with either ngRoute or UI Router and then not change it. This issue is just to remove the option to be able to "switch" between routers. It was included to make things easier to test, but isn't used for that anymore, so this would only cause issues for users if they tried this.

**Comment by flipjs** [comment]
Thanks for clearing that up for me.

**Comment by xak2000** [comment]
I agree about routers but I use scope instead of controllerAs. If in the future I want start using controllerAs, can I just start using it in new modules and refactor old modules when have free time after this change? I don't want first refactor all existing modules and only then start using contollerAs in new modules. It will be too much time to refactor all at once.

**Comment by dustinspecker** [comment]
Yes, you can do that now, actually. If you edit the `controllerAs` property stored in your project's `.yo-rc.json`, ng-poly will use that for all future generated files.

I'll get something added to the README about that, too.

**Comment by xak2000** [comment]
Yes, I know that. But my worries is: Can I do that when you implement changes in this issue?

**Comment by dustinspecker** [comment]
Oh, sorry. Yes, you will be able to still do that. ng-poly will still support controllerAs and $scope alternatives at the initial project scaffold and by modifying the `.yo-rc.json`. You just won't be able to pass `--controller-as` to each command because ng-poly will *only* look at the `.yo-rc.json`.

**Comment by xak2000** [comment]
Oh, thanks! Then I positive for this changes as consistency is important.
