### ISSUE TITLE
There are another font extension `woff2` that we need to add to fonts filter

### ISSUE THREAD

**Issue by xak2000** [dustinspecker/generator-ng-poly#185]
For example if we don't copy `glyphicons-halflings-regular.woff2` from bootstrap, then when we open index.html, chrome console prints error:
> GET http://192.168.250.3:3000/vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 

I think this file is requested by `bootstrap.css`, then it fallback to use font with another extension. For this reason all works fine even with this error. But why not include this font file extension in build script? I can open a pull request if you want.

**Comment by dustinspecker** [comment]
Good catch! A PR would be greatly appreciated.
