### ISSUE TITLE
Using sass/bootstrap-sass configuring and loading from app/app.scss

### ISSUE THREAD

**Issue by jancel** [dustinspecker/generator-ng-poly#187]
I'd like to customize bootstrap and use imports from it.  I removed bootstrap, added bootstrap-sass and would like to make sure the build can find app.scss and I can reference bootstrap-sass/assets/_bootstrap.scss.

What should this take, wiredep or gulp mods?  I've not dug into the gulp file but i'd imagine I need to overwrite this somehow.

Has anyone ever done this and is there an example? Any best practices or suggestions?

Here is the part of my bowerfile...
```
    "angular-ui-router": "~0.2.10",
     "bootstrap-sass": "~3.3.5",
    "font-awesome": "~4.2.0",
    "lodash": "~3.9.0"
  },
```

**Comment by dustinspecker** [comment]
Sorry for the late response.

I haven't personally done this. It looks like gulp-sass can use an [includesPath](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L45) option.

I should have some time this weekend to look into it, if you haven't found a solution, yet.
