### ISSUE TITLE
Will old node.js version cause an issue?

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#191]
We have old version of node and npm in our server. Node is 0.10.36 and and npm is 1.3.6. Do you think this will cause an issue when building the angular app? When installed yeoman and ngpoly (npm install -g bower gulp yo generator-ng-poly), no issues at all except for a couple of warnings from yeoman doctor saying nodejs and npm are outdated.

So far, I haven't encountered issues but I'm still on the early stage of development. Is it alright if we still use the old version of nodejs or should we upgrade it? Btw, our backend restAPI is based on PHP, so no nodejs. Thanks.

**Comment by dustinspecker** [comment]
Hey. Node 0.10 should work just fine. All of ng-poly's [tests](https://travis-ci.org/dustinspecker/generator-ng-poly) are ran on 0.10, 0.12, and iojs, so you should be clear on that front.

I've only used npm 2.\*, but I would imagine 1.\* would work fine. If doesn't, please let us know.

**Comment by flipjs** [comment]
thanks for the quick reply, dustin.
