### ISSUE TITLE
Renaming module?

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#192]
I renamed my main module (root folder called app) manually and also updated some files that reference the module. But whenever I create a directive or services on the main module, it still uses the old name. Where can I find the config so I can also change the module name from there, so YO will generate the correct module name. Thanks.

**Comment by dustinspecker** [comment]
Sorry the late response.

Currently, ng-poly looks at the name in `package.json` to determine the root level module name. Sorry for the inconvenience.

I'm going to mark this as an enhancement as what you expected to happen seems like a reasonable assumption.

**Comment by flipjs** [comment]
No worries. Im not at work for a couple of days now anyway. Thanks for the reply.

**Comment by dustinspecker** [comment]
Released in [v0.11.0](https://github.com/dustinspecker/generator-ng-poly/releases/tag/v0.11.0).
