### ISSUE TITLE
Can I safely update from 0.10.11 to 0.10.14?

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#193]
Can I safely update the generator from 0.10.11 to 0.10.14? I asked because yeoman shows a notification that there's an update available. Thanks.

**Comment by dustinspecker** [comment]
Yes, you should be able to. If for some reason it's not, please let us know.

For future reference, we try to follow semantic versioning. When there are breaking releases, we try to explain how to update your app, so you can safely update ng-poly.

**Comment by flipjs** [comment]
Thanks Dustin!
