### ISSUE TITLE
jquery is not the first module in minified vendor js

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#195]
I was having issues with angular-bootstrap-switch (element.bootstrap-switch is not a function error) when building the production code. It turns out that, in the minified vendor file, angular was the very first, before jquery. No issues when doing gulp default because jquery is the first.  So, I had to do 'bower install jquery --save' and make sure it is the first dependency in bower.json. Problem solved!

**Comment by xak2000** [comment]
Specially for this I have this code block in my bower.json:
```
  "overrides": {
    "angular": {
      "dependencies": {
        "jquery": "1.9+"
      }
    },
    "angular-i18n": {
      "main": "angular-locale_ru-ua.js",
      "dependencies": {
        "angular": "*"
      }
    },
    "angular-bootstrap-toggle-switch": {
      "dependencies": {
        "angular": "1.3+"
      }
    },
    "moment": {
      "main": [
        "moment.js",
        "locale/ru.js"
      ]
    },
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js",
        "dist/fonts/glyphicons-halflings-regular.eot",
        "dist/fonts/glyphicons-halflings-regular.svg",
        "dist/fonts/glyphicons-halflings-regular.ttf",
        "dist/fonts/glyphicons-halflings-regular.woff",
        "dist/fonts/glyphicons-halflings-regular.woff2"
      ]
    }
```

`generator-ng-poly` uses `wiredep` module for resolution dependencies and determine their order. Angular's bower.json not declares explicit dependency on jQuery as it can work without it, but `angular-bootstrap-toggle-switch` can't. Of course you can just override `angular-bootstrap-toggle-switch` to depend on jQuery but in my project this causes problems: after js concatenation jQuery was before `angular-bootstrap-toggle-switch` but after `angular`. And angular used jquery-lite. So I modified my bower.json and explicitly declared that `angular-bootstrap-toggle-switch` depends on `angular` and `angular` depends on `jquery`.

**Comment by dustinspecker** [comment]
Thank you for the info guys.

@flipjs, I *think* it's a coincidence that explicitly listing jQuery as a dep in `bower.json` fixed the issue (unless you meant you provided the override). @xak2000's override should guarantee it works.

We should probably modify the default scaffolded `bower.json` to add jQuery as a dep for Angular if Bootstrap is being used. This issue has come up quite a few times already.

**Comment by flipjs** [comment]
Thank you both. Will update my bower.json and use @xak2000 's config as guide.
