### ISSUE TITLE
[angular/ng_di] You should use the function syntax for DI

### ISSUE THREAD

**Issue by flipjs** [dustinspecker/generator-ng-poly#196]
I am getting this error from gulp-eslint when using the value service for arrays. Here's the code:

```
  angular
    .module('home')
    .value('myArray', [{
      name: 'fizz',
      email: 'fizz@example.com'
    }, {
      name: 'buzz',
      email: 'buzz@example.com'
    }]);
```

But when I change the service to constant (same code, just the literal word 'value' changed to 'constant'), no errors reported when I run gulp. So for now, I only use constant.

**Comment by dustinspecker** [comment]
I'm going to close this as it's a bug with `eslint-plugin-angular` and you've posted an issue there, as well.

You can also disable the rule in your `.eslintrc` file until a fix is out.
