### ISSUE TITLE
favicon.ico not copying to build/app

### ISSUE THREAD

**Issue by xak2000** [dustinspecker/generator-ng-poly#198]
I tried to add `favicon.ico` file to my `app` folder and it not copied to `build/app`.
I Added new task for this:

```
  gulp.task('favicon', ['clean'], function () {
    return gulp.src([config.appDir + '/favicon.ico'])
      .pipe(gulp.dest(config.buildDir));
  });
```

and depend `build` task on it:
`gulp.task('build', ['deleteTemplates', 'bowerAssets', 'images', 'fonts', 'favicon']);`

I'm not sure if it is correct approach to make new task for just one file. Maybe we need to add some general task to copy all "common" files.

**Comment by dustinspecker** [comment]
Sorry for the late response.

Your approach works just fine. ng-poly just copies anything from the `images/` directory. So, `images/favicon.ico` *should* be copied.

**Comment by xak2000** [comment]
But `images/` is incorrect location for `favicon.ico` file. By default all browsers looking for it in root of domain. It can be overriden in html `<meta>` tag but not all browsers understand it. So for compatibility we must put `favicon.ico` into web root directory.

My approach works fine for me. But maybe we should put it into generator-ng-poly? It is common case to have `favicon.ico` on any site.

**Comment by dustinspecker** [comment]
Ah, did not realize that. Yep, I agree then. Thanks for the clarification.
