### ISSUE TITLE
When running gulp build --stage prod, hangs after "[11:04:41] Finished 'scripts' after 1.98 s"

### ISSUE THREAD

**Issue by jancel** [dustinspecker/generator-ng-poly#212]
I don't think I have an original gulp file. App was generated with ng-poly in August.  I'm trying to stage for production now, and it's just hanging. Where do I look/debug this type of hang?

**Comment by jancel** [comment]
Related to #144 Since removing the delete task, it runs good.

**Comment by jancel** [comment]
Well, just digging in some more.  Removing that list of task actually short circuits the entire build process.  So I put it back in.  The files I see in the build folder are similar to dev, except the app.js is minified with a map file.  Nothing else to report just yet.

**Comment by jancel** [comment]
Turns out, I had a custom styles directory for all of the sass.  Once I renamed it to stylez (with the app.scss updated), it fired perfectly.

**Comment by dustinspecker** [comment]
Delete task can hang if you've updated `del` recently to `v2.0.0`, I believe. `del` went from a callback to a Promise API recently.

If you come across anything in the future that would make working with Sass easier that ng-poly could do, please let me know.

Thank you for the information.
