### ISSUE TITLE
Cleanup gulp output

### ISSUE THREAD

**Issue by verheyenkoen** [dustinspecker/generator-ng-poly#222]
Is there any way to have this kind of messages removed from the output when you run `gulp analyze`?

```
ESLint found no problems in 1 file
```

Obviously you only want this in case there is no problem.

**Comment by dustinspecker** [comment]
Looked over the docs at [gulp-eslint](https://github.com/adametry/gulp-eslint) and didn't see anything obvious to ignore that. There is a reporter option to consolidate found no problems in all files to a single line.

Might be worth filing a feature request over there.

**Comment by verheyenkoen** [comment]
Apparently this comes from the [eslint-path-formatter](https://github.com/Bartvds/eslint-path-formatter) project (see https://github.com/Bartvds/eslint-path-formatter/blob/master/index.js#L212). Thanks for helping.
