### ISSUE TITLE
Node-sass is outdated

### ISSUE THREAD

**Issue by Isigiel** [dustinspecker/generator-ng-poly#247]
The installed version of node-sass is outdated and has a reference to an invalid location for the prebuilt bindings, causing the style compilation to fail. Currently the only way is to look the file up in it's new location and download it.
I would much appreciate either fixing this problem with additional scripts or a newer version of node-sass (gulp-sass).

**Comment by dustinspecker** [comment]
Thanks for the issue report. Should be fixed in [v0.11.4](https://github.com/dustinspecker/generator-ng-poly/releases/tag/v0.11.4).
