### ISSUE TITLE
Improper handling of data: urls in css

### ISSUE THREAD

**Issue by jancel** [dustinspecker/generator-ng-poly#255]
I posted the question and answer on SO.

http://stackoverflow.com/questions/34885334/gulp-wiredep-builds-with-full-path-prepended-to-base64-images-embedded-in-css/34890670#34890670

Long and short, if you add a bower component that uses compressed base64 images, it won't work per design.  

I fixed the offending javascript:

build.js
```javascript
      .pipe($.if(isProd, $.modifyCssUrls({
        modify: function (url, filePath) {
          if (url.indexOf('http') !== 0 && url.indexOf('data:') !== 0) {
            filePath = path.dirname(filePath) + path.sep;
            filePath = filePath.substring(filePath.indexOf(bowerDir) + bowerDir.length,
              filePath.length);
          } else if (url.indexOf('data:') === 0) {
            // If it's 0, just return it....
            return url;
          }
          url = path.normalize(filePath + url);
          url = url.replace(/[/\\]/g, '/');
          return url;
        }
      })))
```

**Comment by dustinspecker** [comment]
Thanks for the report.

[gulp-modify-css-urls](https://github.com/dustinspecker/gulp-modify-css-urls) should be ignoring data: via this [line](https://github.com/dustinspecker/gulp-modify-css-urls/blob/master/src/index.js#L22). Can you verify which version of gulp-modify-css-urls is installed? v0.2.2 should have the fix.

**Comment by jancel** [comment]
I was looking at the gulp package and these urls (vendor) package never get
processed there.  The offending line of code is in the build.js, is it
possible that this code is part of a different library?

On Wed, Jan 20, 2016 at 5:15 AM, Dustin Specker <notifications@github.com>
wrote:

> Thanks for the report.
>
> gulp-modify-css-urls
> <https://github.com/dustinspecker/gulp-modify-css-urls> should be
> ignoring data: via this line
> <https://github.com/dustinspecker/gulp-modify-css-urls/blob/master/src/index.js#L22>.
> Can you verify which version of gulp-modify-css-urls is installed? v0.2.2
> should have the fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dustinspecker/generator-ng-poly/issues/255#issuecomment-173174965>
> .
>



-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com

**Comment by dustinspecker** [comment]
Oh, yeah. I believe you're right, this is an issue. I'll get your change added and released. Thank you!
