### ISSUE TITLE
devDependencies: true not working

### ISSUE THREAD

**Issue by jboothe** [dustinspecker/generator-ng-poly#256]
When adding the line `devDependencies: true,` to line# 171 of gulp/build.js, devDependencies from bower.json are not pulled into the project via wiredep. 
```
return gulp.src(config.buildDir + 'index.html')
        .pipe($.wiredep.stream({
          devDependencies: true,
          exclude: [/bootstrap[.]js/],
          ...
```
Is there something specific with your gulp files that may cause this or is this a wiredep issue? 

Thanks for your insight.

**Comment by jboothe** [comment]
Solved it. 

Wiredep was injecting the proper file refs into the html page but mainBowerFiles needed to know to what files to target. Adding `{includeDev: true}` to mainBowerFiles on line 115 did the trick. 

```
return gulp.src($.mainBowerFiles({includeDev: true}),
```

**Comment by dustinspecker** [comment]
Glad to hear. Thank you for providing the solution.
