### ISSUE TITLE
Implement directives as classes when using TypeScript

### ISSUE THREAD

**Issue by Jeffarese** [dustinspecker/generator-ng-poly#316]
To fully use the benefits of TypeScript, it would be good to implement directives as classes, as shown here:

http://stackoverflow.com/questions/23535994/implementing-angularjs-directives-as-classes-in-typescript

**Comment by dustinspecker** [comment]
That makes sense especially with how ng2's components are looking.

I'm not sure when I'll have time to make these changes, but if anyone is up making a PR that would be awesome.

**Comment by Jeffarese** [comment]
I'll try to make an approach myself and make a PR ;)

**Comment by Jeffarese** [comment]
#325 Here's my approach, I'm using it on my app and it's working pretty well ;)
