### ISSUE TITLE
Edit or Disable Indent Checks on Linters

### ISSUE THREAD

**Issue by 34r7h** [dustinspecker/generator-ng-poly#355]
Hey Dustin,

Trying to clean up my environment and having some trouble isolating which linter is responsible for throwing indent errors. I've tried setting "indent" properties on eslint and jshint to false and removed them from the object but continue to get the following errors on each file.

Could this be from WebStorm IDE and not your generator?

WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(2,2):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(8,2):
[angular/ng_di] You should use the function syntax for DI
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(8,2):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(10,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(11,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(12,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(13,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(14,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(15,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(16,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(17,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(18,4):
[indent] Expected indentation of 2 space characters but found 0.
WARNING at /Users/i/Apps/scannabis.com/app/app-module.es6(19,4):
[indent] Expected indentation of 2 space characters but found 0.

**Comment by dustinspecker** [comment]
That looks like ESLint for sure. I'm not sure if WebStorm is interfering somehow.

Just to verify, in the `.eslintrc` file, are you overriding indent like:

``` json

{
   "rules": {
     "indent": 0
   }
}
```

I'm not familiar with WebStorm, so it might be causing problems.

I'm currently on vacation, so I apologize if my future responses are delayed.

**Comment by 34r7h** [comment]
That's it! Thanks I was setting the wrong parameter.
