### ISSUE TITLE
Use sourcemaps

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/generator-ng-poly#38]
~~1. Bower components that have a sourcemap should have sourcemaps moved to build/~~
1. Sourcemaps should be created when compiling (style, etc.), concatenating, and minifying (CSS, JS)
1. Created sourcemaps should be placed in build

**Comment by wilsonwc** [comment]
I have a simple solution using gulp-sourcemaps which embeds the sourcemaps into the end of the app-xxxxxx.js file in production.  I'll try to do a PR tonight
