### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ngbinh** [dustinspecker/generator-ng-poly#51]
- [X] Test for TypeScript app  
 - [X] Modify build to support TypeScript
 - [x] Use `tsd` to automatically pull in references
 - [x] Test for TypeScript modules, controller and route
 - [x] Correct implementation of route utils
 - [x] Correct TypeScript templates
 - [x] Support other types

**Comment by ngbinh** [comment]
FYI, I've been using TypeScript in ng-poly in production for a while without major problem. Obviously, the module system can be improved but it is not a major problem for us.

**Comment by dustinspecker** [comment]
That's great to hear. Do you guys have any suggestions for improving the modules?

The Gulpfiles have been updated to build the app and tests in a tmp directory for unit tests. The templates are updated. Unfortunately, there is an issue with angular-protractor and jQuery conflicting (https://github.com/borisyankov/DefinitelyTyped/issues/2734) for e2e tests.

**Comment by ngbinh** [comment]
Awesome! Thanks a lot! I will update our build to the latest version.
