### ISSUE TITLE
Template Partials Moved to /build on --stage prod

### ISSUE THREAD

**Issue by jboothe** [dustinspecker/generator-ng-poly#68]
Partials are still moved when creating a production build even though nghtml2js correctly stuffing partials into app-[version].js. Verified the app works correctly when deleting the files off of disk. 

This is not a big issue but could get messy deleting many partials and nested partials when executing deployment workflows.

**Comment by dustinspecker** [comment]
b38696430d4303287706d64731ab348a36bb5482 *way* overdue, but finally implemented
