### ISSUE TITLE
Have a cachebuster

### ISSUE THREAD

**Issue by amolghotankar** [dustinspecker/generator-ng-poly#96]
There is a typical caching issue. For both dev & prod we may want to have a cache buster query string which gets updated everytime we build or deploy.

Something like http://localhost/app.js?cachebuster=<somelongnumber> and generate and use this <somelongnumber> in index.html to refer all js with such query string

Generate this <somelongnumber> everytime a new gulp build command runs. Append it to all js & then include it at all places in index.html.

Also when we update single file we may want to go ahead and update the file in build folder then also update its <somelongnumber> in query string

**Comment by dustinspecker** [comment]
We do something similar for production builds already.

To implement this on dev, remove the isProd condition from gulp/build.js on [line 91](https://github.com/dustinspecker/generator-ng-poly/blob/0dacd1612bed32a10e4cce8638494b17f1423201/app/templates/_build.js#L91) and [line 122](https://github.com/dustinspecker/generator-ng-poly/blob/0dacd1612bed32a10e4cce8638494b17f1423201/app/templates/_build.js#L122). Gulp will inject these files automatically.

gulp-rev changes the file name from app.js to app-SOME_CHARS.js, etc.
